### PR TITLE
Typos in zone_sun.tab

### PR DESCRIPTION
**Pull request by pbdigital-dot-org**
fixes problems when using installer.
for more info see:
https://illumos.topicbox.com/groups/omnios-discuss/Tf2062ccdce7d8628/kayak-installer-usr-share-lib-zoneinfo-tab-zonesun-tab

### CODE REVIEW

**Comment by citrus-it** [comment]
@pbdigital-dot-org Thanks for finding this and reporting the problem!

The illumos project does not take PRs for this repository; there's a contributing guide at https://illumos.org/docs/contributing/ if you want to go down that path, or I'd be willing to take your patch and put it through the integration process - we need to get this into the upcoming OmniOS r151034 release anyway.

I did a quick sanity check on the zone after applying this patch and it looks like there might be a couple more to fix up too (these will need cross-referencing with `zone.tab.txt` in the same directory)

```
% egrep -v '^#' zone_sun.tab| nawk -F "\t" 'NF > 5 { print }'
AR      -3436-05827     America/Argentina/Buenos_Aires  -       America/Buenos_Aires    Buenos Aires (BA, CF)
US      +515248-1763929 America/Adak    US/Aleutian     -       Aleutian Islands
US      +211825-1575130 Pacific/Honolulu        -       US/Hawaii       Hawaii
```

Some of the following may be okay, but others (like the last one) have the - in the wrong field:

```
% egrep -v '^#' zone_sun.tab| nawk -F "\t" 'NF < 4 || $4 != "-" { print }'
AR      -2411-06518     America/Argentina/Jujuy America/Jujuy   Jujuy (JY)
AR      -2828-06547     America/Argentina/Catamarca     America/Catamarca      Catamarca (CT); Chubut (CH)
AR      -3253-06849     America/Argentina/Mendoza       America/Mendoza Mendoza (MZ)
AS      -1416-17042     Pacific/Pago_Pago       US/Samoa
AU      -3133+15905     Australia/Lord_Howe     Australia/LHI   Lord Howe Island
AU      -3749+14458     Australia/Melbourne     Australia/Victoria      Victoria
AU      -3455+13835     Australia/Adelaide      Australia/South South Australia
AU      -1228+13050     Australia/Darwin        Australia/North Northern Territory
BR      -0351-03225     America/Noronha Brazil/DeNoronha        Atlantic islands
BR      -0958-06748     America/Rio_Branco      Brazil/Acre     Acre
CL      -2709-10926     Pacific/Easter  Chile/EasterIsland      Easter Island
IR      +3540+05126     Asia/Tehran     Iran
IS      +6409-02151     Atlantic/Reykjavik      Iceland
US      +515248-1763929 America/Adak    US/Aleutian     -       Aleutian Islands
```

**Comment by pbdigital-dot-org** [comment]
Hi Andy, 
Go ahead with the patch, I am sure you will be more efficient than I. I am happy to have helped this far.
Philip

**Comment by citrus-it** [comment]
I pushed a review up to https://code.illumos.org/c/illumos-gate/+/496
I think these are actually the only typos, some of the things you moved to field 5 are actually canonical zone names that belong in field 4 as far as I can tell.

(The OmniOS installer might separately need some updates to handle more of the zone information)

**Comment by citrus-it** [comment]
The changes have been merged as https://github.com/illumos/illumos-gate/commit/63878f749f68d1c188363e0e7a36e7b7e855dff2

Thanks again for finding this issue.

**Pull request closed without merging**
