### PR TITLE
hw_serial cleanup: remove remains of misc/sysinit removed in 2008, make it uint32_t since every user parses it anyway

### PR DESCRIPTION
**Pull request by nabijaczleweli**

### CODE REVIEW

**Comment by danmcd** [comment]
This show promise, but we don't use github PRs in illumos.  Please consult:  https://illumos.org/docs/contributing/ and ping the developer list.  We can use this as a review-source, but illumos-gate's process isn't github.

**Comment by nabijaczleweli** [comment]
Well I did see a good few merged PRs so I fingered I'd try, and illumos.org lists this repo but not the list, so hardly a different avenue from the out-set.

**Comment by nabijaczleweli** [comment]
Yeah, nah, I'm not signing up for two accounts and begging Some Guy To Champion My Thing just to post two patches.

**Comment by gdamore** [comment]
So the sysinit method to load host ids may be used in third party distributions. I know of at least one case that did this. 

I also have some other compatibility concerns around this PR. I don’t think the benefits justify the risks.

**Comment by jclulow** [comment]
> Yeah, nah, I'm not signing up for two accounts and begging Some Guy To Champion My Thing just to post two patches.

Hi!  I don't believe you will need two accounts, just an illumos bug tracker account.  Our Gerrit instance uses the same accounts as the bug tracker, for instance.  I don't believe you need to create an account for the mailing lists, just subscribe with your existing email.

There shouldn't be any need to beg anybody; if you post to the mailing list for review we'll take a look and work with you to figure out how to proceed!  You can probably just post a link to this PR to get started, even though we don't generally use PRs to actually merge things.

We're also available in `#illumos` on Libera IRC if you'd like to chat.

**Comment by gdamore** [comment]
Why was my comment above marked *off topic*.  It specifically addressed concerns I have with the nature of this PR (whether it comes in via the normal process following Gerrit or this.)

There have been (and may still be!) third party consumers who use the misc/sysinit module (using non-public code) to override the calculation of the host ID.   The changed proposed here would break them, although the API is not "documented".  The misc/sysinit mechanism is the only easy way they have to influence the calculated hostid without forking illumos proper.

There may also be consumers who rely upon the hostid being a string elsewhere.

Changing the implementation here seems to me to bring very little or no value, and risks breaking things that are already working for people.

**Pull request closed without merging**
