### PR TITLE
4057 Add sfxge support

### PR DESCRIPTION
**Pull request by gdamore**
Contributed by Solarflare
Reviewed by: TBD
Approved by: TBD

(I know we don't do PRs, but this is one alternative for code review... please feel free to comment on this.  I will post a formal webrev and maybe review board later.)

This also facilitates anyone else who wants to merge this change into their own tree for testing.

### CODE REVIEW

**Comment by j-trash** [comment]
using your sfxge port just after the first release appeared on github, so far no problems with 10G (sadly i got no possibility to test 40G)

**Comment by sjorge** [comment]
👍 for a PR experimen, let's see how this goes. (Or did you already do the traditional webrev)

**Comment by gdamore** [comment]
I did webrev… RTI is pending.  I found a bug and am waiting for test and
review feedback.

**Comment by ip1981** [comment]
I hope I will never see merge-commits here.

**Comment by gdamore** [comment]
Huh?  Why is that a particular concern?

**Comment by ip1981** [comment]
They are just noise.

**Comment by gdamore** [comment]
Igor.  Dude.  I actually was the one that ensured we had a no merge policy for the gate.  Merged in my own tree always get squashed.  I actually find the insinuation that I don't know that offensive.  I guess maybe you forgot that I am the founder for illumos.

**Comment by gdamore** [comment]
This going thru formal rti right now.

**Comment by ip1981** [comment]
AFAIK, PRs can only be merged at Github, so when I saw this PR.. I thought the heaven is falling :-)

**Comment by sjorge** [comment]
@ip1981 you can actually get a patch for  given PR too.

e.g. https://github.com/illumos/illumos-gate/pull/16.patch

**Comment by gdamore** [comment]
If you looked at the comment I did say that the PR was filed only for review and not for integration.

**Comment by gdamore** [comment]
Further you can merge PRs by hand as ff commits using the git command line.  The github gui sucks here but it does offer command line instructions so you can see how to use git properly from the command prompt.

**Pull request closed without merging**
