### PR TITLE
Update smbns_ads.c to add aditional help

### PR DESCRIPTION
**Pull request by schenklklopfer**
removed typo
added additional help to check local system time.
This was the issue the last few hours with my setup.
So I think this hint might be helpful.

### CODE REVIEW

**Comment by danmcd** [comment]
We don't do PRs in illumos-gate, but I've created https://www.illumos.org/issues/8687  to track this.  I can help you guide this in as your first commit to illumos-gate.

**Comment by schenklklopfer** [comment]
Thanks. I didn't knew.

Is there anything I need to do now?

**Comment by danmcd** [comment]
Since this is so small, I'd just mail the diff and the bug pointer to the illumos developer's list and get a code reviewer on it.  Then submit an RTI:  https://wiki.illumos.org/display/illumos/RTI+Advocacy+Process  which for something this small is just an email, proof of building, and proof of testing.  I can help with all of this, BTW.

**Comment by schenklklopfer** [comment]
I can't proof the build neither the testing stuff.
It is just a changed string that can be seen in case of an error.

The idea was just to help other ones getting this error and can't find the solution because "Wrong Password" is just not the only possible answer. I did hours of research to find it.
I thought this might be the best way to help others instead of writing a blog entry nobody will ever find googling this error.

**Comment by danmcd** [comment]
Okay then.  I'll run with this, crediting where appropriate.  Watch your mails.

**Comment by danmcd** [comment]
>  I did hours of research to find it.

Did you skew clocks and try things?  SPelling out what you did will be helpful.

**Comment by schenklklopfer** [comment]
Problem was installing it in VMware ESXi 6.5 and the time sync between Host and Guest didn't work.
Because of Time Zone problem there was a difference of two hours.

Setting the time via date to a nearly correct time fixed this.
I think using a NTP will fix this as well.

**Comment by gwr** [comment]
I think we have some similar fixes for time sync. issues in
https://github.com/Nexenta/illumos-nexenta
(I'd look on the release-4.0.5-FP branch.)
Any chance you might have time to check?
If so, that would save us some merge conflicts.
Thanks!

**Pull request closed without merging**
